# Generated by Django 2.1.5 on 2019-04-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='date',
        ),
    ]
