# Generated by Django 2.2 on 2019-05-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0005_currentfile_downloadedfile_prepross'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentFile',
        ),
        migrations.DeleteModel(
            name='DownloadedFile',
        ),
        migrations.DeleteModel(
            name='Prepross',
        ),
    ]
