# Generated by Django 2.2 on 2019-08-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0009_auto_20190806_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='notes',
            new_name='inputcols',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='title',
            new_name='targetcols',
        ),
    ]
