# Generated by Django 2.1.5 on 2020-01-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0013_auto_20200114_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
