# Generated by Django 2.1.5 on 2020-01-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0015_remove_userdetails_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table='userdetails',
        ),
    ]
