# Generated by Django 2.1.5 on 2020-01-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0016_auto_20200123_0728'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetails',
            table=None,
        ),
    ]
