# Generated by Django 2.1.5 on 2020-02-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0017_auto_20200123_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='inputcols',
            field=models.CharField(max_length=100),
        ),
    ]
