# Generated by Django 2.1.5 on 2020-04-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0018_auto_20200206_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataCleaningModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeType', models.CharField(max_length=100)),
            ],
        ),
    ]
