# Generated by Django 2.1.5 on 2020-04-03 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0019_datacleaningmodels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacleaningmodels',
            old_name='changeType',
            new_name='changeColTypeTo',
        ),
        migrations.AddField(
            model_name='datacleaningmodels',
            name='changeTypeCol',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
