# Generated by Django 3.0.6 on 2020-06-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0021_auto_20200530_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='replaceNaNvaluesMoedels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colName', models.CharField(max_length=100)),
                ('replaceNanvaluesWith', models.IntegerField()),
            ],
        ),
    ]
