# Generated by Django 3.0.6 on 2020-06-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0022_replacenanvaluesmoedels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='replaceNaNvaluesMoedels',
            new_name='replaceNaNvaluesModels',
        ),
    ]
