# Generated by Django 2.1.5 on 2020-06-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0023_auto_20200603_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replacenanvaluesmodels',
            old_name='replaceNanvaluesWith',
            new_name='replacevaluesWith',
        ),
        migrations.AddField(
            model_name='replacenanvaluesmodels',
            name='valueToBeReplaced',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
