# Generated by Django 2.1.5 on 2020-09-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearningApi', '0024_auto_20200616_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacenanvaluesmodels',
            name='Random_Shuffle',
            field=models.BooleanField(default=True),
        ),
    ]
